spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: labo-team-axes
          uri: lb://LABO-TEAM-AXES
          predicates:
            - Path=/api/ltx/**


        - id: department-event
          uri: lb://DEPARTMENT-EVENT
          predicates:
            - Path=/api/de/**

        - id: department-etablissement
          uri: lb://DEPARTMENT-ETABLISSEMENT
          predicates:
            - Path=/api/ed/**

        - id: ecole-doctorale
          uri: lb://ECOLE-DOCTORALE
          predicates:
            - Path=/api/ecole-doctorale/**

        - id: filier
          uri: lb://FILIER
          predicates:
            - Path=/api/filiers/**

        - id: formation
          uri: lb://FORMATION
          predicates:
            - Path=/api/formations/**

        - id: group-section
          uri: lb://GROUP-SECTION
          predicates:
            - Path=/api/gs/**

        - id: student-service
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/api/students/**

        - id: module-service
          uri: lb://MODULE-SERVICE
          predicates:
            - Path=/api/m/**

        - id: recherche-event
          uri: lb://RECHERCHE-EVENT
          predicates:
            - Path=/api/eventR/**

        - id: researcher-service
          uri: lb://RESEARCHER-SERVICE
          predicates:
            - Path=/api/researcher/**

        - id: semestre
          uri: lb://SEMESTER
          predicates:
            - Path=/api/as/**

      globalcors:
        corsConfigurations:
          '[/]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods: "GET, POST, PUT, DELETE"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

